# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/tri/Documents/HK1NAM4/HWSW/project/project_2/project_2.srcs/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_xbar_0/zynq_interrupt_system_xbar_0.xci
# IP: The module: 'zynq_interrupt_system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tri/Documents/HK1NAM4/HWSW/project/project_2/project_2.srcs/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_xbar_0/zynq_interrupt_system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_interrupt_system_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/tri/Documents/HK1NAM4/HWSW/project/project_2/project_2.srcs/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_xbar_0/zynq_interrupt_system_xbar_0.xci
# IP: The module: 'zynq_interrupt_system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tri/Documents/HK1NAM4/HWSW/project/project_2/project_2.srcs/sources_1/bd/zynq_interrupt_system/ip/zynq_interrupt_system_xbar_0/zynq_interrupt_system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_interrupt_system_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
